name: Python check

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/check.yml'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'pdm.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/check.yml'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'pdm.lock'
  merge_group:
  workflow_dispatch:

# concurrency:
#   group: ${{ github.ref }}-${{ github.workflow }}
#   cancel-in-progress: true

# env:
#   CARGO_TERM_COLOR: always
#   SCCACHE_GHA_ENABLED: true
#   RUSTC_WRAPPER: sccache

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pdm sync -d -G lint
    - name: Run Lint Checks
      run: |
        pdm run checklint

  test:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pdm sync -d

    - name: Start Postgres
      run: |
        docker run --name pgvecto-rs-demo -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d tensorchord/pgvecto-rs:latest
    
    - name: Run Tests
      run: |
        pdm run test