name: Python Release

on:
#   push:
#     tags:
#       - "v*"
  schedule:
    # 00:00 UTC+8 -> 16:00
    - cron: "0 16 * * *"
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python_release.yml'

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3

    - name: Publish package distributions to PyPI
      working-directory: bindings/python
      run: pdm publish